# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-31 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('when_created', models.DateTimeField()),
                ('verbose_title', models.CharField(blank=True, max_length=200)),
                ('verbose_date', models.CharField(blank=True, max_length=50)),
                ('head', models.TextField()),
                ('body', models.TextField()),
                ('slug', models.SlugField(max_length=20, unique=True)),
            ],
        ),
    ]
