# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-05 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioentry',
            name='is_index',
            field=models.BooleanField(default=False),
        ),
    ]
