# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-23 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolioentry_is_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioentry',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
