# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-10 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolioentry_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioentry',
            options={'verbose_name_plural': 'Portfolio entries'},
        ),
    ]
