# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-10 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20161010_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioentry',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='portfolioentry',
            name='when_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
